spring.application.name=API-Gateway
#spring cloud gate config
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true


#Routing logic product

spring.cloud.gateway.routes[0].id=product-api
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/place

spring.cloud.gateway.routes[1].id=notification-api
spring.cloud.gateway.routes[1].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/notification

server.port=3333